[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Jacob Van De Weert <vandeweertj@gmail.com>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[dependencies]
lazy_static = "1.4"
regex = "1.4"
